ecomerceapi/admin.py, ecomerceapi/apps.py, ecomerceapi/models.py, ecomerceapi/tests.py, ecomerceapi/views.py, ecommerceapi/models/customer.py, ecommerceapi/models/order.py, ecommerceapi/models/orderproduct.py, ecommerceapi/models/paymenttype.py, ecommerceapi/models/product.py, ecommerceapi/models/producttype.py
Made models
Check that models are good
=> Mb initial branch

ecommerceapi/fixtures/customer.json, ecommerceapi/fixtures/order.json, ecommerceapi/fixtures/orderproduct.json, ecommerceapi/fixtures/paymenttype.json, ecommerceapi/fixtures/product.json, ecommerceapi/fixtures/producttype.json, ecommerceapi/models/product.py
git checkout mg-3
python manage.py loaddata customers
try all fixtures make sure they work
=> fixed fixtures

ecommerceapi/views/product.py
git checkout mg-homepage 
check product?total=3 returns all products
=> last 20 product displaying on homepage

bangazonllc/urls.py, ecommerceapi/views/__init__.py, ecommerceapi/views/customer.py, ecommerceapi/views/user.py
git checkout mr-mc-coolCustomer
go to Postman and get "/customers/1"
check that the depth is working on the users property
change to an update with url as "/customers/1"
copy paste the data from your get into the update and change something about your data
ensure the update method works
=> Mr mc cool customer

bangazonllc/settings.py, bangazonllc/urls.py, ecommerceapi/models/paymenttype.py, ecommerceapi/views/__init__.py, ecommerceapi/views/paymenttype.py
- Installed soft delete package and added it to list of installed apps in admin app's 'settings.py' file. 
- Updated product type model to use the safedelete model, and then made a new migration.
- To install safe delete run this command in root directory of project in the terminal: 
'pip install django-safedelete'
- Once installed run: 
'python manage.py makemigrations'
'python manage.py migrate'
- Should be able to: 1) See a list of payment types, 2) Create a payment type, 3) Delete a payment type
- When deleting a payment type, check the paymenttype table to see that the payment type should still be there, but a new column called "deleted" should be added to the end of the row, with a date of when it was deleted... This is called a soft delete and it's what most databases actually do …
=> Ts add payment type

bangazonllc/urls.py, ecommerceapi/models/product.py, ecommerceapi/views/__init__.py, ecommerceapi/views/customer.py, ecommerceapi/views/paymenttype.py, ecommerceapi/views/product.py, ecommerceapi/views/producttype.py
make sure you can view /producttypes
=> Mb branch3

bangazonllc/urls.py, ecommerceapi/models/order.py, ecommerceapi/views/order.py, ecommerceapi/views/orderproduct.py
git checkout mg-order-viewset
python manage.py makemigrations
python mange.py migrate
check that you can post and get order
=> Mg order viewset

bangazonllc/urls.py, ecommerceapi/views/__init__.py, ecommerceapi/views/orderproduct.py
order products has conditional to detect existing order or create new one when orderproduct object is created
in postman try POSTing a product_id to /orderproducts
if successful add a payment type to that order to close it out
now POST a product_id to /orderproducts
check the response's order_id to ensure that it is a new order object
=> Mr mc orderstuff

ecommerceapi/views/customer.py, ecommerceapi/views/order.py, ecommerceapi/views/orderproduct.py
git checkout mg-delete 
add orderproduct to order and delete orderproduct and then delete order
=> delete on order and orderproduct

README.md
- Should see instructions for installing Safe Delete in the README.md
=> included instructions for safe delete in the README.md

README.md
- New ERD link should take you to updated DB Diagram
=> updated README with new ERD link

ecommerceapi/views/product.py
- `git fetch --all`
- `git checkout -b ts-12-searchProductType`
1. Run a GET request on products with a query string parameter of 'category' and set it equal to a product_type_id (i.e. `http://127.0.0.1:8000/products?category=1`)
2. Should only see products that match that product_type_id
=> updated product viewset to filter products based on product category

ecommerceapi/models/orderproduct.py, ecommerceapi/views/orderproduct.py
git checkout mb-branch5
python manage.py makemigrations
python manage.py migrate
check your database to make sure the orderproduct table has updated with a rating column
Added an update and list method to the orderproduct view. Retrieve a list in postman and then update a rating.
=> Mb branch5

bangazonllc/urls.py, ecommerceapi/models/orderproduct.py, ecommerceapi/views/order.py, ecommerceapi/views/orderproduct.py
git checkout mg-orderhistory 
python manage.py makemigrations 
python manage.py migrate 
GET /orders to see which orders do not have payment type and double check that you are posting to whatever order that is listed for the user you are logged in as 
POST to /orderproducts that does NOT have a paymenttype 
got to database and add payment type to that order 
GET /orders check to see if orderproducts is nested in the data
=> Mg orderhistory

bangazonllc/urls.py, ecommerceapi/models/__init__.py, ecommerceapi/models/productrec.py, ecommerceapi/views/__init__.py, ecommerceapi/views/productrec.py
built out ProductRecs
added:
./views/productrec.py
./models/productrec.py
productrecs route in urls.py 
git checkout mc-recommendProduct
python manage.py makemigrations
python manage.py migrate
in postman localhost8000/productrecs
-open two tabs with tokens for two users
post a new productrec in each tab
{
"reciever_id": int (not the active user),
"product_id": int
}
get(retrieve) the added productrec
-localhost8000/productrecs/{newly created product rec id
get a list of the users productrecs
GET localhost8000/productrecs
-this should show the product recs for the tokened user in the postman tab
=> product recommendations built, productrec view model and stuff

bangazonllc/urls.py, ecommerceapi/models/product.py, ecommerceapi/views/__init__.py, ecommerceapi/views/product.py, ecommerceapi/views/sellersproducts.py
- `git fetch --all`
- `git checkout ts-15-ProductStatus`
_Changes_
- Added 'MyProducts' viewset in sellersproduct.py and registered the endpoint
- Added 'sold_products = 0' property to the Product model
_Test_
1. Make a GET request to '/myproducts' endpoint and provide a token for the logged-in user (make sure the user has products with customer_id that matches the logged-in user)
2. Make sure those products for the logged-in user are also in the orderproduct table (this is how we know how many times the product has been added to orders / sold).
3. When you get a response, you should see 1) 'quantity' property, 2) 'sold_products' property.
4. The sold_products property value should match the # of instances that product appears in the orderproduct table
5. When you add a product that …
=> Ts 15 product status

bangazonllc/settings.py, bangazonllc/urls.py, ecommerceapi/models/product.py, ecommerceapi/views/product.py
git checkout mb-photoupload2
pip install pillow
python manage.py makemigrations
python manage.py migrate
I'll walk you through testing in postman
=> photos upload

ecommerceapi/models/orderproduct.py, ecommerceapi/views/producttype.py
checking to see what changes i made and if we need to merge
=> Clark api producttypes

ecommerceapi/views/customer.py, ecommerceapi/views/register.py
git checkout mg-fixCustomer
test in postman /customers with your token and just that customer should be returned
=> Mg fix customer

ecommerceapi/views/product.py
git checkout MP-add-product-fix
line added to product views for customer id
=> Mp add product fix

ecommerceapi/views/product.py
***Has been tested via front-end***
=> user/seller can now see products they've listed for sale

ecommerceapi/views/customer.py
- Fixed account endpoint so now when fetching user's data will fetch user based on user_id FK rather than customer id PK
=> fixed account endpoint 

ecommerceapi/views/product.py
- Can now sell product with $ sign included in the form
=> Product endpoint update
